export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const UPDATE_USER_ADMIN_BEGIN = "UPDATE_USER_ADMIN_BEGIN";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_ERROR = "UPDATE_USER_ADMIN_ERROR";
export const SET_EDIT_USER = "SET_EDIT_USER";

export const GET_ALL_CLINICS_BEGIN = "GET_ALL_CLINICS_BEGIN";
export const GET_ALL_CLINICS_SUCCESS = "GET_ALL_CLINICS_SUCCESS";

export const UPDATE_CLINIC_ADMIN_BEGIN = "UPDATE_CLINIC_ADMIN_BEGIN";
export const UPDATE_CLINIC_ADMIN_SUCCESS = "UPDATE_CLINIC_ADMIN_SUCCESS";
export const UPDATE_CLINIC_ADMIN_ERROR = "UPDATE_CLINIC_ADMIN_ERROR";

export const CREATE_CLINIC_ADMIN_BEGIN = "CREATE_CLINIC_ADMIN_BEGIN";
export const CREATE_CLINIC_ADMIN_SUCCESS = "CREATE_CLINIC_ADMIN_SUCCESS";
export const CREATE_CLINIC_ADMIN_ERROR = "CREATE_CLINIC_ADMIN_ERROR";
export const SET_EDIT_CLINIC = "SET_EDIT_CLINIC";

export const GET_ALL_DOCTORS_BEGIN = "GET_ALL_DOCTORS_BEGIN";
export const GET_ALL_DOCTORS_SUCCESS = "GET_ALL_DOCTORS_SUCCESS";

export const UPDATE_DOCTOR_ADMIN_BEGIN = "UPDATE_DOCTOR_ADMIN_BEGIN";
export const UPDATE_DOCTOR_ADMIN_SUCCESS = "UPDATE_DOCTOR_ADMIN_SUCCESS";
export const UPDATE_DOCTOR_ADMIN_ERROR = "UPDATE_DOCTOR_ADMIN_ERROR";
export const SET_EDIT_DOCTOR = "SET_EDIT_DOCTOR";

export const DELETE_USER_ADMIN_BEGIN = "DELETE_USER_ADMIN_BEGIN";
export const DELETE_CLINIC_ADMIN_BEGIN = "DELETE_CLINIC_ADMIN_BEGIN";
export const DELETE_DOCTOR_ADMIN_BEGIN = "DELETE_DOCTOR_ADMIN_BEGIN";

export const HANDLE_CHANGE = "HANDLE CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const LOGOUT_USER = "LOGOUT_USER";
